export const guides = [
  {
    title: '新手必看攻略',
    level: 'beginner',
    category: '新手入門',
    date: '2026-03-01',
    summary: '整理開局優先順序、每日必做與資源分配方向，適合剛入坑時快速查閱。',
    tags: ['開局', '每日', '資源'],
    route: '/guides/beginner',
    image: '',
  },
  {
    title: '每日任務與週常整理',
    level: 'beginner',
    category: '日常任務',
    date: '2026-03-02',
    summary: '把每天、每週建議完成的項目整理成清單，適合剛開始熟悉遊戲節奏時查看。',
    tags: ['每日', '週常', '獎勵'],
    link: '',
    image: '',
  },
  {
    title: '養成資源分配',
    level: 'intermediate',
    category: '養成',
    date: '2026-03-03',
    summary: '整理角色、思念與素材的培養順序，避免中期資源分散。',
    tags: ['養成', '素材', '角色'],
    link: '',
    image: '',
  },
  {
    title: '活動任務檢查表',
    level: 'intermediate',
    category: '活動',
    date: '2026-03-04',
    summary: '活動期間每天可以照著檢查，避免漏領獎勵或錯過任務進度。',
    tags: ['活動', '任務', '獎勵'],
    link: '',
    image: '',
  },
  {
    title: '高難關卡配置思路',
    level: 'advanced',
    category: '進階戰鬥',
    date: '2026-03-05',
    summary: '整理高難關卡的隊伍配置、屬性搭配與操作重點，適合想挑戰更高分數時查看。',
    tags: ['高難', '配隊', '戰鬥'],
    link: '',
    image: '',
  },
  {
    title: '長期資源規劃',
    level: 'advanced',
    category: '資源規劃',
    date: '2026-03-06',
    summary: '用長期視角整理抽卡、培養與素材保留策略，適合已經穩定遊玩後參考。',
    tags: ['抽卡', '資源', '規劃'],
    link: '',
    image: '',
  },
]

export const guideGroups = [
  {
    id: 'beginner-hunter',
    level: 'beginner',
    title: '新手獵人必看',
    description: '適合剛入坑、正在熟悉系統與每日節奏的獵人。',
  },
  {
    id: 'intermediate-hunter',
    level: 'intermediate',
    title: '中級獵人必看',
    description: '適合已經熟悉基礎玩法，想開始整理養成與活動效率的獵人。',
  },
  {
    id: 'advanced-hunter',
    level: 'advanced',
    title: '高級獵人必看',
    description: '適合想挑戰高難、規劃長期資源與提升細節的獵人。',
  },
]
